name: Build, Test & Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore Diogenes.Web.sln

    - name: Build
      run: dotnet build Diogenes.Web.sln --configuration Release --no-restore -warnaserror

    - name: Test with coverage
      run: dotnet test Diogenes.Web.sln --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./TestResults

    - name: Upload test coverage artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-coverage
        path: ./TestResults